shell = "zsh"

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.dotfiles-defer]
local = '~/.config/zsh/defer'

[plugins.env-path]
inline = 'export PATH="~/.local/bin:$PATH"'

[plugins.env-editor]
inline = 'export EDITOR=vim'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
